using BattMo
using Test

println("test_3d_pouch_amg.jl")
include("test_3d_pouch_amg.jl")
println("test_3d_pouch.jl")
include("test_3d_pouch.jl")
println("test_adjoints.jl")
include("test_adjoints.jl")
println("test_advanced_dict_input.jl")
include("test_advanced_dict_input.jl")
println("test_battmo_app.jl")
include("test_battmo_app.jl")
println("test_cell_parameters.jl")
include("test_cell_parameters.jl")
println("test_cycling_protocols.jl")
include("test_cycling_protocols.jl")
println("test_function_input.jl")
include("test_function_input.jl")
println("test_grid_utilities.jl")
include("test_grid_utilities.jl")
println("test_headless_ui.jl")
include("test_headless_ui.jl")
println("test_initial_state.jl")
include("test_initial_state.jl")
println("test_input_current_series.jl")
include("test_input_current_series.jl")
# println("test_matlab_input.jl")
# include("test_matlab_input.jl")
println("test_printer.jl")
include("test_printer.jl")
println("test_pythoncall.jl")
include("test_pythoncall.jl")
println("test_sei.jl")
include("test_sei.jl")
println("test_sodium_ion.jl")
include("test_sodium_ion.jl")
println("test_temperature_dependence.jl")
include("test_temperature_dependence.jl")
println("test_thermal.jl")
include("test_thermal.jl")
println("test_validation.jl")
include("test_validation.jl")
println("test_voltage_breakdown.jl")
include("test_voltage_breakdown.jl")
