export get_parameter_meta_data


function get_parameter_meta_data()
	meta_data = Dict(
		"Case" => Dict(
			"options" => ["Cylindrical", "Pouch", "CoinCell"],
		),
		"EffectiveDensity" => Dict(
			"type" => Real,
		),
		"SurfaceCoefficientOfHeatTransfer" => Dict(
			"type" => Real,
		),
		"ChargeTransferCoefficient" => Dict(
			"type" => Real,
		),
		"MolarVolume" => Dict(
			"type" => Real,
		),
		"ElectronicDiffusionCoefficient" => Dict(
			"type" => Real,
		),
		"StoichiometricCoefficient" => Dict(
			"type" => Real,
		),
		"IntersticialConcentration" => Dict(
			"type" => Real,
		),
		"InitialThickness" => Dict(
			"type" => Real,
		),
		"Protocol" => Dict(
			"type" => Real,
		),
		"RestingTimeAfterCharge" => Dict(
			"type" => Real,
		),
		"RestingTimeAfterDischarge" => Dict(
			"type" => Real,
		),
		"ModelGeometry" => Dict(
			"type" => Real,
		),
		"UseThermalModel" => Dict(
			"type" => Real,
		),
		"UseCurrentCollectors" => Dict(
			"type" => Real,
		),
		"GridPointsPositiveElectrode" => Dict(
			"type" => Real,
		),
		"GridPointsPositiveElectrodeActiveMaterial" => Dict(
			"type" => Real,
		),
		"GridPointsNegativeElectrode" => Dict(
			"type" => Real,
		),
		"GridPointsNegativeElectrodeActiveMaterial" => Dict(
			"type" => Real,
		),
		"GridPointsSeparator" => Dict(
			"type" => Real,
		),
		"Grid" => Dict(
			"type" => Real,
		),
		"UseRampUp" => Dict(
			"type" => Real,
		),
		"RampUpSteps" => Dict(
			"type" => Real,
		),
		"MaximumConcentration" => Dict(
			"context_type" => "MaximumConcentration",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_47287d09_6108_45ca_ac65_8b9451b1065e",
			"max_value" => 100000.0,
			"min_value" => 1000.0,
			"description" => "The saturation concentration of the guest molecule in the host material",
			"type" => Real,
			"unit" => "mol\u00B7m\u207b\u00b3",
			"unit_name" => "emmo=>MolePerCubicMetre",
			"unit_iri" => "https=>//w3id.org/emmo=>MolePerCubicMetre"),
		"Area" => Dict(
			"context_type" => "VolumetricSurfaceArea",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_a5571263_f153_448f_84a3_cd18092cf8fa",
			"max_value" => 10000000.0,
			"min_value" => 1,
			"description" => "Surface area of the material per volume of electrode",
			"type" => Real,
			"unit" => "m\u00b2m\u207b\u00b3",
			"unit_name" => "emmo=>Metre",
			"unit_iri" => "https=>//w3id.org/emmo#Metre",
		),
		"VolumetricSurfaceArea" => Dict(
			"context_type" => "VolumetricSurfaceArea",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_a5571263_f153_448f_84a3_cd18092cf8fa",
			"max_value" => 10000000.0,
			"min_value" => 1,
			"description" => "Surface area of the material per volume of electrode",
			"type" => Real,
			"unit" => "m\u00b2m\u207b\u00b3",
			"unit_name" => "emmo=>Metre",
			"unit_iri" => "https=>//w3id.org/emmo#Metre",
		),
		"Density" => Dict(
			"context_type" => "Density",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_06448f64_8db6_4304_8b2c_e785dba82044",
			"max_value" => 10000.0,
			"min_value" => 100,
			"description" => "",
			"type" => Real,
			"unit" => "kg\u00B7m\u207b\u00b3",
			"unit_name" => "emmo=>GramPerCubicMetre",
			"unit_iri" => "https=>//w3id.org/emmo#GramPerCubicMetre",
		),
		"SpecificHeatCapacity" => Dict(
			"context_type" => "SpecificHeatCapacity",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_b4f4ed28_d24c_4a00_9583_62ab839abeca",
			"max_value" => 10000.0,
			"min_value" => 10,
			"description" => "",
			"type" => Real,
			"unit" => "J\u00B7kg\u207b\u00b9\u00B7K\u207b\u00b9",
			"unit_name" => "emmo=>JoulePerKiloGramKelvin",
			"unit_iri" => "https=>//w3id.org/emmo#JoulePerKiloGramKelvin",
		),
		"ThermalConductivity" => Dict(
			"context_type" => "ThermalConductivity",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_8dd40ec6_2c5a_43f3_bf64_cadcd447a1c1",
			"max_value" => 1000.0,
			"min_value" => 0.01,
			"description" => "",
			"type" => Real,
			"unit" => "W\u00B7m\u207b\u00b9\u00B7K\u207b\u00b9",
			"unit_name" => "emmo=>WattPerMetreKelvin",
			"unit_iri" => "https=>//w3id.org/emmo#WattPerMetreKelvin",
		),
		"ElectronicConductivity" => Dict("context_type" => "ElectricConductivity",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_cde4368c_1d4d_4c94_8548_604749523c6d",
			"max_value" => 7e7,
			"min_value" => 0.1,
			"description" => "The electronic conductivity of the material",
			"type" => Real,
			"unit" => "S\u00B7m\u207b\u00b9",
			"unit_name" => "emmo=>SiemensPerMetre",
			"unit_iri" => "https=>//w3id.org/emmo#SiemensPerMetre",
		),
		"NumberOfElectronsTransferred" => Dict("context_type" => "NumberOfEntities",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_41efdf5d_0c9c_4ea0_bb65_f8236e663be5",
			"max_value" => 1,
			"min_value" => 1,
			"description" => "stoichiometric number of electrons transferred in the electrochemical reaction",
			"type" => Int,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"ActivationEnergyOfReaction" => Dict("context_type" => "Energy",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_31ec09ba_1713_42cb_83c7_b38bf6f9ced2",
			"max_value" => 100000.0,
			"min_value" => 1,
			"description" => "the activation energy of the electrochemical reaction",
			"type" => Real,
			"unit" => "J\u00B7mol\u207b\u00b9\u00B7",
			"unit_name" => "emmo=>JoulePerMole",
			"unit_iri" => "https=>//w3id.org/emmo#JoulePerMole",
		),
		"ReactionRateConstant" => Dict("context_type" => "ReactionRateConstant",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_0335e3f6_d1d8_4daa_8376_a9285f1bc9f1",
			"max_value" => 0.001,
			"min_value" => 1e-20,
			"description" => "the reaction rate constant of the electrochemical reaction", "type" => Real,
			"unit" => "mol\u00B7m\u207b\u00b2\u00B7s\u207b\u00b9",
			"unit_name" => "emmo=>MolePerSquareMetrePerSecond",
			"unit_iri" => "https=>//w3id.org/emmo#MolePerSquareMetrePerSecond",
		),
		"StoichiometricCoefficientAtSOC100" => Dict("context_type" => "StoichiometricNumberOfSubstance",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_cbba91a7_d639_461f_ae23_d021751029e4",
			"max_value" => 1,
			"min_value" => 0.01,
			"description" => "the maximum stoichiometry of the guest molecule in the host material at the chosen electric potential limit", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"StoichiometricCoefficientAtSOC0" => Dict("context_type" => "StoichiometricNumberOfSubstance",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_cbba91a7_d639_461f_ae23_d021751029e4",
			"max_value" => 0.999,
			"min_value" => 0.01,
			"description" => "the maximum stoichiometry of the guest molecule in the host material at the chosen electric potential limit", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"ActivationEnergyOfDiffusion" => Dict("context_type" => "ActivationEnergy",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_d7f8cab9_b035_4ecd_be63_292672572526",
			"max_value" => 100000.0,
			"min_value" => 0,
			"description" => "activation energy for diffusion of the guest molecule in the host material", "type" => Real,
			"unit" => "J\u00B7mol\u207b\u00b9\u00B7",
			"unit_name" => "emmo=>JoulePerMole",
			"unit_iri" => "https=>//w3id.org/emmo#JoulePerMole"),
		"diffusion_pre_exponential_factor" => Dict("max_value" => 1,
			"min_value" => 1e-15,
			"description" => "", "type" => Real,
			"unit" => "s\u207b\u00b9",
			"unit_name" => "emmo=>ReciprocalSecond",
			"unit_iri" => "https=>//w3id.org/emmo#ReciprocalSecond"),
		"ParticleRadius" => Dict("context_type" => "ParticleRadius",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_b92e382f_5109_4f60_ab5e_c89d340419a9",
			"max_value" => 1e-3,
			"min_value" => 1e-7,
			"description" => "radius of the material particle", "type" => Real,
			"unit" => "m",
			"unit_name" => "emmo=>Metre",
			"unit_iri" => "https=>//w3id.org/emmo#Metre"),
		"OpenCircuitVoltage" => Dict("context_type" => ["OpenCircuitVoltage", "Expression"],
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_9c657fdc_b9d3_4964_907c_f9a6e8c5f52b",
			"dscription" => "the open-circuit potential of the active material under given concentration and temperature conditions",
			"type" => Function,
			"unit" => "V",
			"unit_name" => "emmo=>Volt",
			"unit_iri" => "https=>//w3id.org/emmo#Volt"),
		"AmbientCelsiusTemperature" => Dict("context_type" => "AmbientThermodynamicTemperature",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_39a44af0_0e1a_4859_b550_bdabad64386e",
			"max_value" => 373.15,
			"min_value" => 238.15,
			"description" => "the ambient temperature of the environment around the battery", "type" => Real,
			"unit" => "K",
			"unit_name" => "emmo=>Kelvin",
			"unit_iri" => "https=>//w3id.org/emmo#Kelvin"),
		"initial_temperature" => Dict("context_type" => "InititalThermodynamicTemperature",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_9c9b80a4_a00b_4b91_8e17_3a7831f2bf2f",
			"max_value" => 373.15,
			"min_value" => 238.15,
			"description" => "", "type" => Real,
			"unit" => "K",
			"unit_name" => "emmo=>Kelvin",
			"unit_iri" => "https=>//w3id.org/emmo#Kelvin"),
		"HeatTransferCoefficient" => Dict("context_type" => "CoefficientOfHeatTransfer",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_43b349fc_c7ed_480d_b0ca_9db84b700813",
			"max_value" => 10000,
			"min_value" => 100,
			"description" => "", "type" => Real,
			"unit" => "W\u00B7m\u207b\u00b2\u00B7K\u207b\u00b9",
			"unit_name" => "emmo=>WattPerSquareMetreKelvin",
			"unit_iri" => "https=>//w3id.org/emmo#WattPerSquareMetreKelvin"),
		"NominalCapacity" => Dict("context_type" => "NominalCapacity",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
			"max_value" => 1000,
			"min_value" => 0,
			"description" => "",
			"is_shown_to_user" => false,
			"type" => Real,
			"unit" => "mAh",
			"unit_name" => "emmo=>AmpereHour",
			"unit_iri" => "https=>//w3id.org/emmo#AmpereHour"),
		"DeviceSurfaceArea" => Dict("context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_47ab1dad_cc09_4fd8_af23_acb36fb680dd",
			"max_value" => 10,
			"min_value" => 1e-06,
			"description" => "", "type" => Real,
			"unit" => "m\u00b2",
			"unit_name" => "emmo=>SquareMetre",
			"unit_iri" => "https=>//w3id.org/emmo#SquareMetre"),
		"Volume" => Dict("context_type" => "Volume",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
			"max_value" => 0.01,
			"min_value" => 1e-06,
			"description" => "", "type" => Real,
			"unit" => "m\u00b3",
			"unit_name" => "emmo=>CubicMetre",
			"unit_iri" => "https=>//w3id.org/emmo#CubicMetre"),
		"BruggemanCoefficient" => Dict("context_type" => "BruggemanCoefficient",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_5c34b3b5_c9c4_477d_809a_3f682f995aa9",
			"max_value" => 5,
			"min_value" => 0.1,
			"description" => "The Bruggeman coefficient for calculating effective transport parameters in porous media", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"NominalCapacity" => Dict("context_type" => "Capacity",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_791c1915_a791_4450_acd8_7f94764743b5",
			"max_value" => 100,
			"min_value" => 0.0,
			"description" => "",
			"is_shown_to_user" => false,
			"type" => Real,
			"unit" => "mAh",
			"unit_name" => "emmo=>MilliAmpereHour",
			"unit_iri" => "https=>//w3id.org/emmo#MilliAmpereHour"),
		"MassFraction" => Dict("context_type" => "MassFraction",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_a8eb87b5_4d10_4137_a75c_e04ee59ca095",
			"max_value" => 1.0,
			"min_value" => 0.01,
			"description" => "Mass fraction of the material", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"ChargeNumber" => Dict("context_type" => "ChargeNumber",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_dc467621_3b49_4f31_9b09_82290f29da52",
			"max_value" => 1,
			"min_value" => 1,
			"description" => "charge number of the ion", "type" => Int,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"TransferenceNumber" => Dict("context_type" => "IonTransportNumber",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_d97b27cb_61a4_4568_a38b_4edd4f224acc",
			"max_value" => 0.99,
			"min_value" => 0.01,
			"description" => "charge trensference of the ion in the electrolyte", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"Concentration" => Dict("context_type" => "IonConcentration",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_8177eae6_1631_430d_99f2_942669bcb784",
			"max_value" => 10000,
			"min_value" => 0.0,
			"description" => "", "type" => Real,
			"unit" => "mol\u00B7L\u207b",
			"unit_name" => "emmo=>MolPerLiter",
			"unit_iri" => "https=>//w3id.org/emmo#MolePerCubicDeciMetre"),
		"IonicConductivity" => Dict(
			"context_type" => ["IonicConductivity", "Expression"],
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_25dabdc2_68bf_4a38_8cbe_11be017358bc",
			"description" => "the ionic conductivity of the electrolyte under given concentration and temparture conditions",
			"type" => Function,
			"unit" => "S\u00B7cm\u207b",
			"unit_name" => "emmo=>SiemensPerCentiMetre",
			"unit_iri" => "https=>//w3id.org/emmo#SiemensPerCentiMetre"),
		"DiffusionCoefficient" => Dict("context_type" => ["DiffusionCoefficient", "Expression"],
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_931a725b_926d_4f60_8955_61fe17fce98b",
			"unit" => "A\u00B7t\u207b",
			"unit_name" => "emmo=>AreaPerTimeUnit",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_10f703b5_8b2a_4c5a_a734_f0cfb29622ad",
			"description" => "the diffusion coefficient of the charge carrier in the electrolyte",
			"type" => Function),
		"Thickness" => Dict("context_type" => "Thickness",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656",
			"max_value" => 500,
			"min_value" => 0.1e-6,
			"description" => "The thickness of the active material coating", "type" => Real,
			"unit" => "\u03BCm",
			"unit_name" => "emmo=>MicroMetre",
			"unit_iri" => "https=>//w3id.org/emmo#MicroMetre"),
		"StartWithCharge" => Dict(
			"description" => "",
			"type" => "str",
		),
		"InitialStateOfCharge" => Dict("context_type" => "StateOfCharge",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/battery#battery_17591da0_34ec_41b9_b3c1_3a4446dc6f0a",
			"max_value" => 1,
			"min_value" => 0.01,
			"description" => "SOC, state of charge of the battery, where 1 is fully charged and 0 is fully discharged", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"TotalNumberOfCycles" => Dict("context_type" => "NumberOfEntities",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_41efdf5d_0c9c_4ea0_bb65_f8236e663be5",
			"max_value" => 100,
			"min_value" => 1,
			"description" => "", "type" => Int,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"DRate" => Dict("context_type" => "DischargingCRate",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_25e20915_c35d_4bee_ad31_736235a79780",
			"max_value" => 10,
			"min_value" => 0.01,
			"description" => "", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"CRate" => Dict("context_type" => "CRate",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_e1fd84eb_acdb_4b2c_b90c_e899d552a3ee",
			"max_value" => 10,
			"min_value" => 0.01,
			"description" => "", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"),
		"LowerVoltageLimit" => Dict("context_type" => "LowerVoltageLimit",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
			"max_value" => 4,
			"min_value" => 0,
			"description" => "lower voltage limit of the battery cell", "type" => Real,
			"unit" => "V",
			"unit_name" => "emmo=>Volt",
			"unit_iri" => "https=>//w3id.org/emmo#Volt"),
		"UpperVoltageLimit" => Dict("context_type" => "UpperVoltageLimit",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
			"max_value" => 5,
			"min_value" => 3,
			"description" => "", "type" => Real,
			"unit" => "V",
			"unit_name" => "emmo=>Volt",
			"unit_iri" => "https=>//w3id.org/emmo#Volt"),
		"CurrentChangeLimit" => Dict("max_value" => 0.1,
			"min_value" => 0.00001,
			"description" => "", "type" => Real,
			"unit" => "A\u00B7s\u207b\u00b9"),
		"VoltageChangeLimit" => Dict("max_value" => 0.1,
			"min_value" => 0.00001,
			"description" => "", "type" => Real,
			"unit" => "V\u00B7s\u207b\u00b9",
			"unit_name" => "emmo=>VoltPerSecond",
			"unit_iri" => "https=>//w3id.org/emmo#VoltPerSecond"),
		"TimeStepDuration" => Dict("max_value" => 1000,
			"min_value" => 1,
			"context_type" => "StepDuration",
			"context_type_iri" => "https=>//w3id.org/emmo/domain/electrochemistry#electrochemistry_85e39686_9658_4c74_bb91_a935704c174a",
			"description" => "",
			"type" => Real, "unit" => "s",
			"unit_name" => "emmo=>Second",
			"unit_iri" => "https=>//w3id.org/emmo/domain/emmo#Second",
		),
		"Porosity" => Dict("context_type" => "Porosity",
			"context_type_iri" => "https=>//w3id.org/emmo#EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9",
			"max_value" => 0.9,
			"min_value" => 0.1,
			"description" => "porosity of the separator", "type" => Real,
			"unit" => "1",
			"unit_name" => "emmo=>UnitOne",
			"unit_iri" => "https=>//w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978"))
	return meta_data
end
