export get_cell_parameters_meta_data


function get_cell_parameters_meta_data()
	meta_data = Dict(
		"Case" => Dict(
			"type" => String,
			"options" => ["Cylindrical", "Pouch"],
			"context_type" => "hasCase",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_3dcfe33d_6825_43c0_a798_68e871a68d39",
			"description" => "Type of physical container encapsulating the electrochemical cell. Examples: Cylindrical, Pouch.",
		),
		"EffectiveDensity" => Dict(
			"type" => Real,
			"min_value" => 0.0,
			"max_value" => 23.0e3,
			"unit" => "kg·m⁻³",
			"unit_name" => "emmo:KilogramPerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#KilogramPerCubicMetre",
			"context_type" => "EffectiveDensity",
			"context_type_iri" => nothing,
			"description" => "Density of a porous electrode, calculated from its geometrical volume and mass. It includes the volume occupied by pores.",
		),
		"NominalVoltage" => Dict(
			"type" => Real,
			"min_value" => 0.0,
			"max_value" => 6.0,
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
			"context_type" => "NominalVoltage",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_639b844a_e801_436b_985d_28926129ead6",
			"description" => "Reference voltage of the cell as reported by the manufacturer. Usually calculated from the cell's energy output and capacity under a standard cycling test.",
		),
		"TabFractions" => Dict(
			"type" => Vector,
			"unit" => "-",
			"unit_name" => "dimensionless",
			"unit_iri" => "https://w3id.org/emmo#Dimensionless",
			"context_type" => "TabFractions",
			"description" => "Location of the tabs. The location of each tab is given by a fraction which determines the fraction of the total spiral length where the tab is located.",
		),
		"InnerRadius" => Dict(
			"type" => Real,
			"min_value" => 0.001,
			"max_value" => 0.1,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "InnerRadius",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_32dcd601_47c7_4028_b7fa_5e972ae57f12",
			"description" => "Radius of the rolled electrodes within a cylindrical cell, measured from the center of the cell to the inner side of the cell wall.",
		),
		"OuterRadius" => Dict(
			"type" => Real,
			"min_value" => 0.001,
			"max_value" => 0.2,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "OuterRadius",
			"description" => "Radius of the rolled electrodes within a cylindrical cell, measured from the center of the cell to the outer side of the cell wall.",
		),
		"ElectrodeWidth" => Dict(
			"type" => Real,
			"min_value" => 0.01,
			"max_value" => 0.5,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "Width",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
			"description" => "Dimension of the shortest side of the face of a rectangular electrode.",
		),
		"ElectrodeLength" => Dict(
			"type" => Real,
			"min_value" => 0.01,
			"max_value" => 0.5,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "Length",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
			"description" => "Dimension of the longest side of the face of a rectangular electrode.",
		),
		"Height" => Dict(
			"type" => Real,
			"min_value" => 0.01,
			"max_value" => 0.5,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "Length",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
			"description" => "The heigh of a cylindrical cell.",
		),
		"SurfaceCoefficientOfHeatTransfer" => Dict(
			"type" => Real,
			"min_value" => 1.0,
			"max_value" => 5000,
			"unit" => "W·m⁻²·K⁻¹",
			"unit_name" => "emmo:WattPerSquareMetreKelvin",
			"unit_iri" => "https://w3id.org/emmo#WattPerSquareMetreKelvin",
			"context_type" => "SurfaceCoefficientOfHeatTransfer",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_0b3295fa_f4bf_4f83_a603_9d98c03da5bb",
			"description" => "Rate at which heat is exchanged between a cell’s surface and its surrounding environment",
		),
		"ChargeTransferCoefficient" => Dict(
			"type" => Real,
			"min_value" => 0.1,
			"max_value" => 0.9,
			"unit" => "-",
			"unit_name" => "dimensionless",
			"unit_iri" => "https://w3id.org/emmo#Dimensionless",
			"context_type" => "ChargeTransferCoefficient",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a4dfa5c1_55a9_4285_b71d_90cf6613ca31",
			"description" => "Constant alpha in the Butler-Volmer equation. It represents the fraction of the electrostatic potential energy affecting the reduction rate in an electrode reaction, with the remaining fraction affecting the corresponding oxidation rate.",
		),
		"MolarVolume" => Dict(
			"type" => Real,
			"min_value" => 1e-6,
			"max_value" => 0.03,
			"unit" => "m³·mol⁻¹",
			"unit_name" => "emmo:CubicMetrePerMole",
			"unit_iri" => "https://w3id.org/emmo#CubicMetrePerMole",
			"context_type" => "MolarVolume",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_8b4af754_110a_4854_ac65_349ebafc1bed",
			"description" => "Volume per amount of substance.",
		),
		"ElectronicDiffusionCoefficient" => Dict(
			"type" => Real,
			"min_value" => 1.0e-16,
			"max_value" => 1.0e3,
			"unit" => "m²·s⁻¹",
			"unit_name" => "emmo:SquareMetrePerSecond",
			"unit_iri" => "https://w3id.org/emmo#SquareMetrePerSecond",
			"context_type" => "ElectronicDiffusionCoefficient",
			"context_type_iri" => nothing,
			"description" => "Diffusion coefficient of electrons in a solid.",
		),
		"StoichiometricCoefficient" => Dict(
			"type" => Real,
			"min_value" => 0.0,
			"max_value" => 10.0,
			"unit" => "-",
			"unit_name" => "dimensionless",
			"unit_iri" => "https://w3id.org/emmo#Dimensionless",
			"context_type" => "StoichiometricCoefficient",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_f0667139_6428_4e3d_ac0d_08c1dd7f36ea",
			"description" => "Ratio of the concentration of an intercalant (e.g. Li+) at a given moment, to its maximum possible concentration within a solid host material.",
		),
		"InterstitialConcentration" => Dict(
			"type" => Real,
			"min_value" => 0.0,
			"max_value" => 1.0e5,
			"unit" => "mol·m⁻³",
			"unit_name" => "emmo:MolePerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#MolePerCubicMetre",
			"context_type" => "InterstitialConcentration",
			"context_type_iri" => nothing,
			"description" => "Amount of neutral intersticial sites of the intercalant (Li+) per volume of solid. See https://doi.org/10.1002/cssc.201800077.",
		),
		"InitialThickness" => Dict(
			"type" => Real,
			"min_value" => 1e-9,
			"max_value" => 1e-2,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "InitialThickness",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656",
			"description" => "Thickness of the SEI layer at the start of the simulation. See https://doi.org/10.1016/j.powera.2022.100083.",
		),
		"InitialPotentialDrop" => Dict(
			"type" => Real,
			"min_value" => 0,
			"max_value" => 1,
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
			"context_type" => "InitialPotentialDrop",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_654321",
			"description" => "Electric potential difference across the SEI layer or electrode interface at the beginning of the simulation. Represents any initial voltage offset due to pre-formation or initial conditions of the cell.",
		),
		"TabWidth" => Dict(
			"type" => Real,
			"min_value" => 0.0005,
			"max_value" => 0.5,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_e4de48b1_dabb_4490_ac2b_040f926c64f0",
			"description" => "Dimension of the shortest side of the face of the rectangular tab of a current collector.",
		),
		"TabLength" => Dict(
			"type" => Real,
			"min_value" => 0.0001,
			"max_value" => 0.5,
			"unit" => "m",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_cd2cd0de_e0cc_4ef1_b27e_2e88db027bac",
			"description" => "Dimension of the longest side of the face of the rectangular tab of a current collector.",
		),
		"MaximumConcentration" => Dict(
			"context_type" => "MaximumConcentration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47287d09_6108_45ca_ac65_8b9451b1065e",
			"max_value" => 1.0e6,
			"min_value" => 0.0,
			"description" => "The saturation concentration of the guest molecule in the host material",
			"type" => Real,
			"unit" => "mol·m⁻³",
			"unit_name" => "emmo:MolePerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#MolePerCubicMetre",
		),
		"ElectrodeGeometricSurfaceArea" => Dict(
			"context_type" => "ElectrodeGeometricSurfaceArea",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_fa7790d6_07bb_4b0f_9965_55966828f5f3",
			"max_value" => 2.0,
			"min_value" => 1.0e-4,
			"description" => "Face (or plate) area of an electrode. Electrode cross-sectional area.",
			"type" => Real,
			"unit" => "m²",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"VolumetricSurfaceArea" => Dict(
			"context_type" => "VolumetricSurfaceArea",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a5571263_f153_448f_84a3_cd18092cf8fa",
			"max_value" => 1.0e9,
			"min_value" => 1.0e-3,
			"description" => "Ratio of the electrochemically-active surface area of the electrode per volume of electrode",
			"type" => Real,
			"unit" => "m²m⁻³",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"Density" => Dict(
			"context_type" => "Density",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_06448f64_8db6_4304_8b2c_e785dba82044",
			"max_value" => 1.0e5,
			"min_value" => 1.0e-2,
			"description" => "Density of the material.",
			"type" => Real,
			"unit" => "kg·m⁻³",
			"unit_name" => "emmo:GramPerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#GramPerCubicMetre",
		),
		"SpecificHeatCapacity" => Dict(
			"context_type" => "SpecificHeatCapacity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_b4f4ed28_d24c_4a00_9583_62ab839abeca",
			"max_value" => 2.0e4,
			"min_value" => 1.0e2,
			"description" => "Heat capacity of the material per unit of mass.",
			"type" => Real,
			"unit" => "J·kg⁻¹·K⁻¹",
			"unit_name" => "emmo:JoulePerKiloGramKelvin",
			"unit_iri" => "https://w3id.org/emmo#JoulePerKiloGramKelvin",
		),
		"ThermalConductivity" => Dict(
			"context_type" => "ThermalConductivity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_8dd40ec6_2c5a_43f3_bf64_cadcd447a1c1",
			"max_value" => 1.0e4,
			"min_value" => 1.0e-2,
			"description" => "Material property characterizing its ability to transmit heat through a surface element.",
			"type" => Real,
			"unit" => "W·m⁻¹·K⁻¹",
			"unit_name" => "emmo:WattPerMetreKelvin",
			"unit_iri" => "https://w3id.org/emmo#WattPerMetreKelvin",
		),
		"ElectronicConductivity" => Dict(
			"context_type" => "ElectricConductivity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_cde4368c_1d4d_4c94_8548_604749523c6d",
			"max_value" => 1.0e9,
			"min_value" => 1.0e-20,
			"description" => "Measure of a material's ability to conduct an electric current.",
			"type" => Real,
			"unit" => "S·m⁻¹",
			"unit_name" => "emmo:SiemensPerMetre",
			"unit_iri" => "https://w3id.org/emmo#SiemensPerMetre",
		),
		"ActivationEnergyOfReaction" => Dict(
			"context_type" => "Energy",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_d7f8cab9_b035_4ecd_be63_292672572526",
			"max_value" => 1.0e6,
			"min_value" => 1.0e3,
			"description" => "Parameter of the empirical Arrhenius formulation, characterizing the exponential temperature dependence of the reaction rate of the material.",
			"type" => Real,
			"unit" => "J·mol⁻¹",
			"unit_name" => "emmo:JoulePerMole",
			"unit_iri" => "https://w3id.org/emmo#JoulePerMole",
		),
		"ReactionRateConstant" => Dict(
			"context_type" => "ReactionRateConstant",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_0335e3f6_d1d8_4daa_8376_a9285f1bc9f1",
			"max_value" => 1e-2,
			"min_value" => 1.0e-14,
			"description" => "Proportionality constant quantifying the rate and direction of a chemical reaction by relating it with the concentration of reactants.",
			"type" => [String, Dict{String, Vector}, Real],
			"unit" => "mol·m⁻²·s⁻¹",
			"unit_name" => "emmo:MolePerSquareMetrePerSecond",
			"unit_iri" => "https://w3id.org/emmo#MolePerSquareMetrePerSecond",
		),
		"StoichiometricCoefficientAtSOC100" => Dict("context_type" => "StoichiometricNumberOfSubstance",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_38ab058e_3912_48c2_a7eb_76d25d000820",
			"max_value" => 1.0,
			"min_value" => 0.0,
			"description" => "Stoichiometry of the intercalant within the host material, at the upper cell voltage limit.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"StoichiometricCoefficientAtSOC0" => Dict("context_type" => "StoichiometricNumberOfSubstance",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_f22bd1ec_faca_4335_92a5_a1687154c622",
			"max_value" => 1.0,
			"min_value" => 0.0,
			"description" => "Stoichiometry of the intercalant within the host material, at the lower cell voltage limit.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"ActivationEnergyOfDiffusion" => Dict("context_type" => "ActivationEnergy",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_d7f8cab9_b035_4ecd_be63_292672572526",
			"max_value" => 1.0e6,
			"min_value" => 1.0e3,
			"description" => "Parameter of the empirical Arrhenius formulation, characterizing the exponential temperature dependence of the diffusion coefficient of the material.",
			"type" => Real,
			"unit" => "J·mol⁻¹",
			"unit_name" => "emmo:JoulePerMole",
			"unit_iri" => "https://w3id.org/emmo#JoulePerMole",
		),
		"diffusion_pre_exponential_factor" => Dict(
			"max_value" => 1.0,
			"min_value" => 1e-15,
			"description" => nothing,
			"type" => Real,
			"unit" => "s⁻¹",
			"unit_name" => "emmo:ReciprocalSecond",
			"unit_iri" => "https://w3id.org/emmo#ReciprocalSecond",
		),
		"ParticleRadius" => Dict("context_type" => "ParticleRadius",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_b92e382f_5109_4f60_ab5e_c89d340419a9",
			"max_value" => 1e-3,
			"min_value" => 1e-8,
			"description" => "Radius of an spherical particle.",
			"type" => Real,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"OpenCircuitPotential" => Dict("context_type" => ["OpenCircuitPotential", "Expression"],
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_9c657fdc_b9d3_4964_907c_f9a6e8c5f52b",
			"description" => "The open-circuit potential of the active material under a given intercalant stoichimetry and temperature.",
			"type" => [String, Dict{String, Vector}, Real],
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
			"documentation" => "https://battmo.org/BattMo.jl/dev/manuals/user_guide/simulation_dependent_input",
		),
		"HeatTransferCoefficient" => Dict("context_type" => "CoefficientOfHeatTransfer",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_43b349fc_c7ed_480d_b0ca_9db84b700813",
			"max_value" => 1.0e6,
			"min_value" => 1.0,
			"description" => "At a point on the surface separating two media with different thermodynamic temperatures, magnitude of the density of heat flow rate divided by the absolute value of temperature difference.",
			"type" => Real,
			"unit" => "W·m⁻²·K⁻¹",
			"unit_name" => "emmo:WattPerSquareMetreKelvin",
			"unit_iri" => "https://w3id.org/emmo#WattPerSquareMetreKelvin",
		),
		"NominalCapacity" => Dict(
			"context_type" => "NominalCapacity",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
			"max_value" => 50,
			"min_value" => 0.0001,
			"description" => "Expected charge capacity of a cell under standard conditions, as defined by the manufacturer.",
			"is_shown_to_user" => false,
			"type" => Real,
			"unit" => "Ah",
			"unit_name" => "emmo:AmpereHour",
			"unit_iri" => "https://w3id.org/emmo#AmpereHour",
		),
		"DeviceSurfaceArea" => Dict(
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47ab1dad_cc09_4fd8_af23_acb36fb680dd",
			"max_value" => 1.0,
			"min_value" => 1.0e-4,
			"description" => "Total external surface area of an electrochemical device.",
			"type" => Real,
			"unit" => "m²",
			"unit_name" => "emmo:SquareMetre",
			"unit_iri" => "https://w3id.org/emmo#SquareMetre",
		),
		"Volume" => Dict(
			"context_type" => "Volume",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
			"max_value" => 1.0e-1,
			"min_value" => 1.0e-6,
			"description" => "Three dimensional space occupied by a material or device.",
			"type" => Real,
			"unit" => "m³",
			"unit_name" => "emmo:CubicMetre",
			"unit_iri" => "https://w3id.org/emmo#CubicMetre",
		),
		"BruggemanCoefficient" => Dict(
			"context_type" => "BruggemanCoefficient",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_5c34b3b5_c9c4_477d_809a_3f682f995aa9",
			"max_value" => 5.0,
			"min_value" => 0.5,
			"description" => "Exponent relating the tortuosity and porosity of porous media.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"MassFraction" => Dict(
			"context_type" => "MassFraction",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_7c055d65_2929_40e1_af4f_4bf10995ad50",
			"max_value" => 1.0,
			"min_value" => 0.0,
			"description" => "Mass of an electrode constituent divided by the total mass of all constituents in the solid mixture.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"ChargeNumber" => Dict(
			"context_type" => "ChargeNumber",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_dc467621_3b49_4f31_9b09_82290f29da52",
			"max_value" => 4,
			"min_value" => 1,
			"description" => "Electric charge of an ion divided by the elementary charge.",
			"type" => Int,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"TransferenceNumber" => Dict(
			"context_type" => "IonTransportNumber",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_e3e78df2_d568_4ab7_8c0d_d3a2ee3ae282",
			"max_value" => 0.99,
			"min_value" => 0.01,
			"description" => "Fraction of the total ionic current in an electrolyte that is carried by lithium ions under the influence of an electric field.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"Concentration" => Dict(
			"context_type" => "IonConcentration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_8177eae6_1631_430d_99f2_942669bcb784",
			"min_value" => 0.0,
			"max_value" => 5000,
			"description" => "Moles of the charge carrier species per cubic meter of electrolyte.",
			"type" => Real,
			"unit" => "mol·m⁻³",
			"unit_name" => "emmo:MolePerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#MolePerCubicMetre",
		),
		"IonicConductivity" => Dict(
			"context_type" => ["IonicConductivity", "Expression"],
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_25dabdc2_68bf_4a38_8cbe_11be017358bc",
			"description" => "Measure of the ionic conduction of ions in the electrolyte under given concentration and temperature conditions",
			"type" => [String, Dict{String, Vector}, Real],
			"unit" => "S·m⁻¹",
			"min_value" => 1.0e-10,
			"max_value" => 1.0e3,
			"unit_name" => "emmo:SiemensPerMetre",
			"unit_iri" => "https://w3id.org/emmo#SiemensPerMetre",
			"documentation" => "https://battmo.org/BattMo.jl/dev/manuals/user_guide/simulation_dependent_input",
		),
		"DiffusionCoefficient" => Dict(
			"context_type" => ["DiffusionCoefficient", "Expression"],
			"context_type_iri" => "https://w3id.org/emmo#EMMO_931a725b_926d_4f60_8955_61fe17fce98b",
			"unit" => "m²·s⁻¹",
			"unit_name" => "emmo:AreaPerTimeUnit",
			"unit_iri" => "https://w3id.org/emmo#EMMO_10f703b5_8b2a_4c5a_a734_f0cfb29622ad",
			"description" => "Proportionality constant between the molar flux of the charge carrier and its negative concentration gradient in a material.",
			"type" => [String, Dict{String, Vector}, Real],
			"documentation" => "https://battmo.org/BattMo.jl/dev/manuals/user_guide/simulation_dependent_input",
		),
		"Thickness" => Dict(
			"context_type" => "Thickness",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656",
			"max_value" => 1.0e-1,
			"min_value" => 1e-6,
			"description" => "The dimension of a battery component measured along the direction of ionic transport, perpendicular to the major surfaces.",
			"type" => Real,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"Porosity" => Dict(
			"context_type" => "Porosity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9",
			"max_value" => 0.95,
			"min_value" => 0.05,
			"description" => "Ratio of the pore volume to the total volume of a porous material.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"NumberOfElectronsTransfered" => Dict(
			"context_type" => "ElectronsTransferred",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_abfadc99_6e43_4d37_9b04_7fc5b0f327ae",
			"max_value" => 4,
			"min_value" => 1,
			"description" => "Number of electrons transferred between an electrode and an entity (ion, molecule) during an electrochemical reaction.",
			"type" => Int,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
	)

	return meta_data
end
