export get_cycling_protocol_meta_data

function get_cycling_protocol_meta_data()

	meta_data = Dict(
		"Protocol" => Dict(
			"type" => String,
			"options" => ["CC", "CCCV", "Function"],
			"context_type" => "Protocol",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_d3e2d213_d078_4b9a_8beb_62f063e57d69",
			"description" => """Type of cycling procedure used to cycle a cell. For instance: Constant Current ("CC"), Constant Current - Constant Voltage ("CCCV").""",
		),
		"FunctionName" => Dict(
			"type" => String,
			"context_type" => "Name",
			"context_type_iri" => "https://schema.org/name",
			"description" => "String of the name of a Julia function.",
		),
		"TotalTime" => Dict(
			"type" => Real,
			"min_value" => 1.0,
			"max_value" => 1.0e9,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo#Second",
			"context_type" => "Time",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_0adabf6f_7404_44cb_9f65_32d83d8101a3",
			"description" => "Maximum duration of the simulation.",
		),
		"InitialControl" => Dict(
			"type" => String,
			"options" => ["charging", "discharging"],
			"context_type" => "Protocol",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_472a0ca2_58bf_4618_b561_6fe68bd9fd49",
			"description" => "Whether a cycling protocol starts with \"charging\" or \"discharging\"."),
		"RestingTimeAfterCharge" => Dict(
			"type" => Real,
			"min_value" => 0.0,
			"max_value" => 1.0e6,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo#Second",
			"context_type" => "RestingTimeAfterCharge",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_2678a656_4a27_4706_8dde_b0a93e9b92fa",
			"description" => "Time during which the cell is kept at open-circuit conditions after completing a charging step.",
		),
		"RestingTimeAfterDischarge" => Dict(
			"type" => Real,
			"min_value" => 0.0,
			"max_value" => 1.0e6,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo#Second",
			"context_type" => "RestingTimeAfterDischarge",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_2678a656_4a27_4706_8dde_b0a93e9b92fa",
			"description" => "Time during which the cell is kept at open-circuit conditions after completing a discharging step.",
		),
		"AmbientTemperature" => Dict("context_type" => "AmbientThermodynamicTemperature",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_39a44af0_0e1a_4859_b550_bdabad64386e",
			"max_value" => 373.15,
			"min_value" => 238.15,
			"description" => "The ambient temperature of the environment surrounding the electrochemical cell.",
			"type" => Real,
			"unit" => "K",
			"unit_name" => "emmo:Kelvin",
			"unit_iri" => "https://w3id.org/emmo#Kelvin",
		),
		"InitialTemperature" => Dict("context_type" => "InititalThermodynamicTemperature",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_9c9b80a4_a00b_4b91_8e17_3a7831f2bf2f",
			"max_value" => 373.15,
			"min_value" => 238.15,
			"description" => "The thermodynamic temperature at some point in time designated to be the initial state.",
			"type" => Real,
			"unit" => "K",
			"unit_name" => "emmo:Kelvin",
			"unit_iri" => "https://w3id.org/emmo#Kelvin",
		),
		"InitialStateOfCharge" => Dict(
			"context_type" => "StateOfCharge",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_8b2aaa50_bbe1_45da_8778_8898326246a2",
			"max_value" => 1.0,
			"min_value" => 0.0,
			"description" => "State of charge of the cell at the start of a simulation.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"TotalNumberOfCycles" => Dict(
			"context_type" => "NumberOfEntities",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_6d981c04_3ace_4f1b_b0f8_770776cceb6f",
			"max_value" => 10000,
			"min_value" => 0,
			"description" => "Total count of charge-discharge cycles executed during the simulation under defined conditions.",
			"type" => Int,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"DRate" => Dict(
			"context_type" => "DischargingCRate",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_25e20915_c35d_4bee_ad31_736235a79780",
			"max_value" => 50,
			"min_value" => 0.001,
			"description" => "An indicator of the electric current at which a cell discharged relative to a defined capacity. 1C corresponds to discharging the entire defined capacity in one hour.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"CRate" => Dict(
			"context_type" => "CRate",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a7dc73e2_d4aa_4dfc_8b4d_cb611f1501fb",
			"max_value" => 50,
			"min_value" => 0.001,
			"description" => "An indicator of the electric current at which a cell discharged relative to a defined capacity. 1C corresponds to charging the entire defined capacity in one hour.",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"LowerVoltageLimit" => Dict(
			"context_type" => "LowerVoltageLimit",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
			"max_value" => 6.0,
			"min_value" => 0.0,
			"description" => "Minimum voltage limit when the discharge step stops.",
			"type" => Real,
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
		),
		"UpperVoltageLimit" => Dict(
			"context_type" => "UpperVoltageLimit",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
			"max_value" => 6.0,
			"min_value" => 1.0,
			"description" => "Maximum voltage limit when the charge step stops.",
			"type" => Real,
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
		),
		"CurrentChangeLimit" => Dict(
			"max_value" => 1.0e-1,
			"min_value" => 1.0e-8,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_71f10616_15eb_4dc4_bc8d_ffaac3838af2",
			"description" => "A control limit placed on the rate of change of the electric current (dI/dt) in a constant-voltage step.",
			"type" => Real,
			"unit" => "A·s⁻¹",
		),
		"VoltageChangeLimit" => Dict(
			"max_value" => 0.1,
			"min_value" => 0.0001,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_09e64707_a17d_4405_84cc_ee9d91ed32ef",
			"description" => "A control limit placed on the rate of change of the cell voltage (dV/dt) in a constant-current step.",
			"type" => Real,
			"unit" => "V·s⁻¹",
			"unit_name" => "emmo:VoltPerSecond",
			"unit_iri" => "https://w3id.org/emmo#VoltPerSecond",
		),
	)

	return meta_data
end
