export get_parameter_meta_data


function get_parameter_meta_data()
	meta_data = Dict(
		"Case" => Dict(
			"type" => String,
			"options" => ["3D-demo", "Cylindrical", "Pouch"],
			"context_type" => "CellCaseType",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_case_type",
		),
		"EffectiveDensity" => Dict(
			"type" => Real,
			"min_value" => 100,
			"max_value" => 1000000,
			"unit" => "kg·m⁻³",
			"unit_name" => "emmo:KilogramPerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#KilogramPerCubicMetre",
			"context_type" => "EffectiveDensity",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_12345",
		),
		"DubbelCoatedElectrodes" => Dict(
			"type" => Bool,
			"context_type" => "DoubleCoatedElectrodes",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_double_coated",
		),
		"NominalVoltage" => Dict(
			"type" => Real,
			"min_value" => 2.5,
			"max_value" => 4.5,
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
			"context_type" => "NominalVoltage",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_67890",
		),
		"InnerCellRadius" => Dict(
			"type" => Real,
			"min_value" => 0.001,
			"max_value" => 0.05,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "InnerCellRadius",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_54321",
		),
		"ElectrodeWidth" => Dict(
			"type" => Real,
			"min_value" => 0.001,
			"max_value" => 0.3,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "Width",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_11223",
		),
		"ElectrodeLength" => Dict(
			"type" => Real,
			"min_value" => 0.01,
			"max_value" => 5,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "Length",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_33445",
		),
		"SurfaceCoefficientOfHeatTransfer" => Dict(
			"type" => Real,
			"min_value" => 5,
			"max_value" => 10000,
			"unit" => "W·m⁻²·K⁻¹",
			"unit_name" => "emmo:WattPerSquareMetreKelvin",
			"unit_iri" => "https://w3id.org/emmo#WattPerSquareMetreKelvin",
			"context_type" => "SurfaceCoefficientOfHeatTransfer",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_55667",
		),
		"ChargeTransferCoefficient" => Dict(
			"type" => Real,
			"min_value" => 0.1,
			"max_value" => 1.5,
			"unit" => "-",
			"unit_name" => "dimensionless",
			"unit_iri" => "https://w3id.org/emmo#Dimensionless",
			"context_type" => "ChargeTransferCoefficient",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_77889",
		),
		"MolarVolume" => Dict(
			"type" => Real,
			"min_value" => 1e-6,
			"max_value" => 1e-4,
			"unit" => "m³·mol⁻¹",
			"unit_name" => "emmo:CubicMetrePerMole",
			"unit_iri" => "https://w3id.org/emmo#CubicMetrePerMole",
			"context_type" => "MolarVolume",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_99112",
		),
		"ElectronicDiffusionCoefficient" => Dict(
			"type" => Real,
			"min_value" => 1e-14,
			"max_value" => 1e-8,
			"unit" => "m²·s⁻¹",
			"unit_name" => "emmo:SquareMetrePerSecond",
			"unit_iri" => "https://w3id.org/emmo#SquareMetrePerSecond",
			"context_type" => "ElectronicDiffusionCoefficient",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_44556",
		),
		"StoichiometricCoefficient" => Dict(
			"type" => Real,
			"min_value" => 0,
			"max_value" => 10,
			"unit" => "-",
			"unit_name" => "dimensionless",
			"unit_iri" => "https://w3id.org/emmo#Dimensionless",
			"context_type" => "StoichiometricCoefficient",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_88990",
		),
		"IntersticialConcentration" => Dict(
			"type" => Real,
			"min_value" => 0,
			"max_value" => 5000,
			"unit" => "mol·m⁻³",
			"unit_name" => "emmo:MolePerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#MolePerCubicMetre",
			"context_type" => "IntersticialConcentration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_123456",
		),
		"InitialThickness" => Dict(
			"type" => Real,
			"min_value" => 1e-9,
			"max_value" => 1e-2,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
			"context_type" => "InitialThickness",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_654321",
		),
		"Protocol" => Dict(
			"type" => String,
			"options" => ["CC", "CCCV"],
			"context_type" => "Protocol",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_789012",
		),
		"InitialControl" => Dict(
			"type" => String,
			"options" => ["charging", "discharging"],
			"context_type" => "Protocol",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_789012",
		),
		"RestingTimeAfterCharge" => Dict(
			"type" => Real,
			"min_value" => 0,
			"max_value" => 3600,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo#Second",
			"context_type" => "RestingTimeAfterCharge",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_345678",
		),
		"RestingTimeAfterDischarge" => Dict(
			"type" => Real,
			"min_value" => 0,
			"max_value" => 3600,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo#Second",
			"context_type" => "RestingTimeAfterDischarge",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_901234",
		),
		"ModelGeometry" => Dict(
			"type" => String,
			"options" => ["1D", "3D Pouch"],
			"context_type" => "ModelGeometry",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_geometry",
		),
		"UseSEIModel" => Dict(
			"type" => String,
			"options" => ["Bolay"],
			"is_sub_model" => true,
		),
		"UseDiffusionModel" => Dict(
			"type" => String,
			"options" => ["PXD"],
			"is_sub_model" => true,
			"documentation" => "https://battmoteam.github.io/BattMo.jl/dev/manuals/user_guide/models",
		),
		"UseCurrentCollectors" => Dict(
			"type" => String,
			"options" => ["Generic"],
			"context_type" => "UseCurrentCollectors",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_current_collectors",
			"is_sub_model" => true,
		),
		"GridPointsElectrodeWidth" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsPositiveElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_positive",
		),
		"GridPointsElectrodeLength" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsPositiveElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_positive",
		),
		"GridPointsPositiveElectrodeCoating" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsPositiveElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_positive",
		),
		"GridPointsPositiveElectrodeActiveMaterial" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsPositiveElectrodeActiveMaterial",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_positive_active",
		),
		"GridPointsNegativeElectrodeCoating" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative",
		),
		"GridPointsPositiveElectrodeCurrentCollector" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative",
		),
		"GridPointsPositiveElectrodeCurrentCollectorTabWidth" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative",
		),
		"TabWidth" => Dict(
			"type" => Real,
			"min_value" => 1e-9,
			"max_value" => 1000),
		"TabLength" => Dict(
			"type" => Real,
			"min_value" => 1e-8,
			"max_value" => 1000,
		),
		"GridPointsPositiveElectrodeCurrentCollectorTabLength" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative",
		),
		"GridPointsNegativeElectrodeCurrentCollector" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative",
		),
		"GridPointsNegativeElectrodeCurrentCollectorTabWidth" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative",
		),
		"GridPointsNegativeElectrodeCurrentCollectorTabLength" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrode",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative",
		),
		"GridPointsNegativeElectrodeActiveMaterial" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsNegativeElectrodeActiveMaterial",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_negative_active",
		),
		"GridPointsSeparator" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridPointsSeparator",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid_separator",
		),
		"Grid" => Dict(
			"type" => Vector,
			"context_type" => "Grid",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_grid",
		),
		"UseRampUp" => Dict(
			"type" => String,
			"options" => ["Sinusoidal"],
			"context_type" => "UseRampUp",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_rampup",
			"is_sub_model" => true,
		),
		"RampUpSteps" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 100,
			"context_type" => "RampUpSteps",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_rampup_steps",
		),
		"MaximumConcentration" => Dict(
			"context_type" => "MaximumConcentration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47287d09_6108_45ca_ac65_8b9451b1065e",
			"max_value" => 100000.0,
			"min_value" => 10000.0,
			"description" => "The saturation concentration of the guest molecule in the host material",
			"type" => Real,
			"unit" => "mol·m⁻³",
			"unit_name" => "emmo:MolePerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#MolePerCubicMetre",
		),
		"ElectrodeGeometricSurfaceArea" => Dict(
			"context_type" => "ElectrodeGeometricSurfaceArea",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a5571263_f153_448f_84a3_cd18092cf8fa",
			"max_value" => 1,
			"min_value" => 0,
			"description" => "Surface area of the material per volume of electrode",
			"type" => Real,
			"unit" => "m²m⁻³",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"VolumetricSurfaceArea" => Dict(
			"context_type" => "VolumetricSurfaceArea",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_a5571263_f153_448f_84a3_cd18092cf8fa",
			"max_value" => 5000000.0,
			"min_value" => 100.0,
			"description" => "Surface area of the material per volume of electrode",
			"type" => Real,
			"unit" => "m²m⁻³",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"Density" => Dict(
			"context_type" => "Density",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_06448f64_8db6_4304_8b2c_e785dba82044",
			"max_value" => 10000.0,
			"min_value" => 100.0,
			"description" => "",
			"type" => Real,
			"unit" => "kg·m⁻³",
			"unit_name" => "emmo:GramPerCubicMetre",
			"unit_iri" => "https://w3id.org/emmo#GramPerCubicMetre",
		),
		"SpecificHeatCapacity" => Dict(
			"context_type" => "SpecificHeatCapacity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_b4f4ed28_d24c_4a00_9583_62ab839abeca",
			"max_value" => 3000.0,
			"min_value" => 50.0,
			"description" => "",
			"type" => Real,
			"unit" => "J·kg⁻¹·K⁻¹",
			"unit_name" => "emmo:JoulePerKiloGramKelvin",
			"unit_iri" => "https://w3id.org/emmo#JoulePerKiloGramKelvin",
		),
		"ThermalConductivity" => Dict(
			"context_type" => "ThermalConductivity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_8dd40ec6_2c5a_43f3_bf64_cadcd447a1c1",
			"max_value" => 100.0,
			"min_value" => 0.001,
			"description" => "",
			"type" => Real,
			"unit" => "W·m⁻¹·K⁻¹",
			"unit_name" => "emmo:WattPerMetreKelvin",
			"unit_iri" => "https://w3id.org/emmo#WattPerMetreKelvin",
		),
		"ElectronicConductivity" => Dict(
			"context_type" => "ElectricConductivity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_cde4368c_1d4d_4c94_8548_604749523c6d",
			"max_value" => 1e8,
			"min_value" => 0.01,
			"description" => "The electronic conductivity of the material",
			"type" => Real,
			"unit" => "S·m⁻¹",
			"unit_name" => "emmo:SiemensPerMetre",
			"unit_iri" => "https://w3id.org/emmo#SiemensPerMetre",
		),
		"ActivationEnergyOfReaction" => Dict(
			"context_type" => "Energy",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_31ec09ba_1713_42cb_83c7_b38bf6f9ced2",
			"max_value" => 200000.0,
			"min_value" => 1000.0,
			"description" => "the activation energy of the electrochemical reaction",
			"type" => Real,
			"unit" => "J·mol⁻¹",
			"unit_name" => "emmo:JoulePerMole",
			"unit_iri" => "https://w3id.org/emmo#JoulePerMole",
		),
		"ReactionRateConstant" => Dict(
			"context_type" => "ReactionRateConstant",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_0335e3f6_d1d8_4daa_8376_a9285f1bc9f1",
			"max_value" => 1e-2,
			"min_value" => 1e-13,
			"description" => "the reaction rate constant of the electrochemical reaction",
			"type" => Real,
			"unit" => "mol·m⁻²·s⁻¹",
			"unit_name" => "emmo:MolePerSquareMetrePerSecond",
			"unit_iri" => "https://w3id.org/emmo#MolePerSquareMetrePerSecond",
		),
		"StoichiometricCoefficientAtSOC100" => Dict("context_type" => "StoichiometricNumberOfSubstance",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_cbba91a7_d639_461f_ae23_d021751029e4",
			"max_value" => 1.0,
			"min_value" => 0.01,
			"description" => "The maximum stoichiometry of the guest molecule in the host material at the chosen electric potential limit",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"StoichiometricCoefficientAtSOC0" => Dict("context_type" => "StoichiometricNumberOfSubstance",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_cbba91a7_d639_461f_ae23_d021751029e4",
			"max_value" => 1.0,
			"min_value" => 0.0,
			"description" => "The minimum stoichiometry of the guest molecule in the host material at the chosen electric potential limit",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"ActivationEnergyOfDiffusion" => Dict("context_type" => "ActivationEnergy",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_d7f8cab9_b035_4ecd_be63_292672572526",
			"max_value" => 100000.0,
			"min_value" => 500.0,
			"description" => "Activation energy for diffusion of the guest molecule in the host material",
			"type" => Real,
			"unit" => "J·mol⁻¹",
			"unit_name" => "emmo:JoulePerMole",
			"unit_iri" => "https://w3id.org/emmo#JoulePerMole",
		),
		"diffusion_pre_exponential_factor" => Dict(
			"max_value" => 1.0,
			"min_value" => 1e-15,
			"description" => "",
			"type" => Real,
			"unit" => "s⁻¹",
			"unit_name" => "emmo:ReciprocalSecond",
			"unit_iri" => "https://w3id.org/emmo#ReciprocalSecond",
		),
		"ParticleRadius" => Dict("context_type" => "ParticleRadius",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_b92e382f_5109_4f60_ab5e_c89d340419a9",
			"max_value" => 1e-3,
			"min_value" => 1e-7,
			"description" => "Radius of the material particle",
			"type" => Real,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"OpenCircuitPotential" => Dict("context_type" => ["OpenCircuitPotential", "Expression"],
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_9c657fdc_b9d3_4964_907c_f9a6e8c5f52b",
			"description" => "The open-circuit potential of the active material under given concentration and temperature conditions",
			"type" => [String, Dict{String, Vector}, Real],
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
		),
		"AmbientKelvinTemperature" => Dict("context_type" => "AmbientThermodynamicTemperature",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_39a44af0_0e1a_4859_b550_bdabad64386e",
			"max_value" => 373.15,
			"min_value" => 238.15,
			"description" => "The ambient temperature of the environment around the battery",
			"type" => Real,
			"unit" => "K",
			"unit_name" => "emmo:Kelvin",
			"unit_iri" => "https://w3id.org/emmo#Kelvin",
		),
		"InitialKelvinTemperature" => Dict("context_type" => "InititalThermodynamicTemperature",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_9c9b80a4_a00b_4b91_8e17_3a7831f2bf2f",
			"max_value" => 373.15,
			"min_value" => 238.15,
			"description" => "",
			"type" => Real,
			"unit" => "K",
			"unit_name" => "emmo:Kelvin",
			"unit_iri" => "https://w3id.org/emmo#Kelvin",
		),
		"HeatTransferCoefficient" => Dict("context_type" => "CoefficientOfHeatTransfer",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_43b349fc_c7ed_480d_b0ca_9db84b700813",
			"max_value" => 10000.0,
			"min_value" => 100.0,
			"description" => "",
			"type" => Real,
			"unit" => "W·m⁻²·K⁻¹",
			"unit_name" => "emmo:WattPerSquareMetreKelvin",
			"unit_iri" => "https://w3id.org/emmo#WattPerSquareMetreKelvin",
		),
		"NominalCapacity" => Dict(
			"context_type" => "NominalCapacity",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_8abde9d0_84f6_4b4f_a87e_86028a397100",
			"max_value" => 100,
			"min_value" => 0.1,
			"description" => "Nominal capacity of the battery in mAh",
			"is_shown_to_user" => false,
			"type" => Real,
			"unit" => "Ah",
			"unit_name" => "emmo:AmpereHour",
			"unit_iri" => "https://w3id.org/emmo#AmpereHour",
		),
		"DeviceSurfaceArea" => Dict(
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47ab1dad_cc09_4fd8_af23_acb36fb680dd",
			"max_value" => 5,
			"min_value" => 0.001,
			"description" => "Surface area of the device",
			"type" => Real,
			"unit" => "m²",
			"unit_name" => "emmo:SquareMetre",
			"unit_iri" => "https://w3id.org/emmo#SquareMetre",
		),
		"Volume" => Dict(
			"context_type" => "Volume",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_f1a51559_aa3d_43a0_9327_918039f0dfed",
			"max_value" => 0.05,
			"min_value" => 0.001,
			"description" => "Volume of the device",
			"type" => Real,
			"unit" => "m³",
			"unit_name" => "emmo:CubicMetre",
			"unit_iri" => "https://w3id.org/emmo#CubicMetre",
		),
		"BruggemanCoefficient" => Dict(
			"context_type" => "BruggemanCoefficient",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_5c34b3b5_c9c4_477d_809a_3f682f995aa9",
			"max_value" => 5,
			"min_value" => 1.0,
			"description" => "The Bruggeman coefficient for calculating effective transport parameters in porous media",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"MassFraction" => Dict(
			"context_type" => "MassFraction",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_a8eb87b5_4d10_4137_a75c_e04ee59ca095",
			"max_value" => 1.0,
			"min_value" => 0.0,
			"description" => "Mass fraction of the material",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"ChargeNumber" => Dict(
			"context_type" => "ChargeNumber",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_dc467621_3b49_4f31_9b09_82290f29da52",
			"max_value" => 1,
			"min_value" => 1,
			"description" => "Charge number of the ion",
			"type" => Int,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"TransferenceNumber" => Dict(
			"context_type" => "IonTransportNumber",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_d97b27cb_61a4_4568_a38b_4edd4f224acc",
			"max_value" => 0.95,
			"min_value" => 0.05,
			"description" => "Charge transference of the ion in the electrolyte",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"Concentration" => Dict(
			"context_type" => "IonConcentration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_8177eae6_1631_430d_99f2_942669bcb784",
			"max_value" => 8000,
			"min_value" => 100,
			"description" => "Ion concentration in the electrolyte",
			"type" => Real,
			"unit" => "mol·L⁻¹",
			"unit_name" => "emmo:MolPerLiter",
			"unit_iri" => "https://w3id.org/emmo#MolePerCubicDeciMetre",
		),
		"IonicConductivity" => Dict(
			"context_type" => ["IonicConductivity", "Expression"],
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_25dabdc2_68bf_4a38_8cbe_11be017358bc",
			"description" => "The ionic conductivity of the electrolyte under given concentration and temperature conditions",
			"type" => [String, Dict{String, Vector}, Real],
			"unit" => "S·cm⁻¹",
			"unit_name" => "emmo:SiemensPerCentiMetre",
			"unit_iri" => "https://w3id.org/emmo#SiemensPerCentiMetre",
		),
		"DiffusionCoefficient" => Dict(
			"context_type" => ["DiffusionCoefficient", "Expression"],
			"context_type_iri" => "https://w3id.org/emmo#EMMO_931a725b_926d_4f60_8955_61fe17fce98b",
			"unit" => "A·t⁻¹",
			"unit_name" => "emmo:AreaPerTimeUnit",
			"unit_iri" => "https://w3id.org/emmo#EMMO_10f703b5_8b2a_4c5a_a734_f0cfb29622ad",
			"description" => "The diffusion coefficient of the charge carrier in the electrolyte",
			"type" => [String, Dict{String, Vector}, Real],
		),
		"Thickness" => Dict(
			"context_type" => "Thickness",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656",
			"max_value" => 1000,
			"min_value" => 1e-6,
			"description" => "The thickness of the active material coating",
			"type" => Real,
			"unit" => "m",
			"unit_name" => "emmo:Metre",
			"unit_iri" => "https://w3id.org/emmo#Metre",
		),
		"StartWithCharge" => Dict(
			"description" => "Starting charge state of the system",
			"type" => Bool,
		),
		"InitialStateOfCharge" => Dict(
			"context_type" => "StateOfCharge",
			"context_type_iri" => "https://w3id.org/emmo/domain/battery#battery_17591da0_34ec_41b9_b3c1_3a4446dc6f0a",
			"max_value" => 1,
			"min_value" => 0.0,
			"description" => "SOC, state of charge of the battery, where 1 is fully charged and 0 is fully discharged",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"TotalNumberOfCycles" => Dict(
			"context_type" => "NumberOfEntities",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_41efdf5d_0c9c_4ea0_bb65_f8236e663be5",
			"max_value" => 1500,
			"min_value" => 0,
			"description" => "Total number of charge-discharge cycles",
			"type" => Int,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"DRate" => Dict(
			"context_type" => "DischargingCRate",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_25e20915_c35d_4bee_ad31_736235a79780",
			"max_value" => 5,
			"min_value" => 0.05,
			"description" => "Rate at which the battery discharges relative to its capacity",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"CRate" => Dict(
			"context_type" => "CRate",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_e1fd84eb_acdb_4b2c_b90c_e899d552a3ee",
			"max_value" => 5,
			"min_value" => 0.05,
			"description" => "Charge rate of the battery relative to its capacity",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"LowerVoltageLimit" => Dict(
			"context_type" => "LowerVoltageLimit",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_534dd59c_904c_45d9_8550_ae9d2eb6bbc9",
			"max_value" => 3.5,
			"min_value" => 1,
			"description" => "Lower voltage limit of the battery cell",
			"type" => Real,
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
		),
		"UpperVoltageLimit" => Dict(
			"context_type" => "UpperVoltageLimit",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_6dcd5baf_58cd_43f5_a692_51508e036c88",
			"max_value" => 4.5,
			"min_value" => 4.0,
			"description" => "Upper voltage limit of the battery cell",
			"type" => Real,
			"unit" => "V",
			"unit_name" => "emmo:Volt",
			"unit_iri" => "https://w3id.org/emmo#Volt",
		),
		"CurrentChangeLimit" => Dict(
			"max_value" => 1.0e-1,
			"min_value" => 1.0e-8,
			"description" => "Limit for changes in current",
			"type" => Real,
			"unit" => "A·s⁻¹",
		),
		"VoltageChangeLimit" => Dict(
			"max_value" => 0.05,
			"min_value" => 0.0001,
			"description" => "Limit for changes in voltage",
			"type" => Real,
			"unit" => "V·s⁻¹",
			"unit_name" => "emmo:VoltPerSecond",
			"unit_iri" => "https://w3id.org/emmo#VoltPerSecond",
		),
		"TimeStepDuration" => Dict(
			"max_value" => 500,
			"min_value" => 10,
			"context_type" => "StepDuration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_85e39686_9658_4c74_bb91_a935704c174a",
			"description" => "Duration of each time step in simulations",
			"type" => Real,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo/domain/emmo#Second",
		),
		"Porosity" => Dict(
			"context_type" => "Porosity",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9",
			"max_value" => 0.8,
			"min_value" => 0.2,
			"description" => "Porosity of the separator",
			"type" => Real,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
		"NumberOfElectronsTransfered" => Dict(
			"context_type" => "ElectronsTransferred",
			"context_type_iri" => "https://w3id.org/emmo#EMMO_39c23d98_3922_46b4_a38a_473342aaf12a",
			"max_value" => 1,
			"min_value" => 1,
			"description" => "Number of electrons transferred during a specific electrochemical reaction or process",
			"type" => Int,
			"unit" => "1",
			"unit_name" => "emmo:UnitOne",
			"unit_iri" => "https://w3id.org/emmo#EMMO_5ebd5e01_0ed3_49a2_a30d_cd05cbe72978",
		),
	)

	return meta_data
end