export get_setting_meta_data


function get_setting_meta_data()
	meta_data = Dict(
		"ModelFramework" => Dict(
			"type" => String,
			"options" => ["P2D", "P4D Pouch", "P4D Cylindrical"],
			"context_type" => "ModelFramework",
			"context_type_iri" => "https://w3id.org/emmo/domain/battery#battery_b1921f7b_afac_465a_a275_26f929f7f936",
			"is_sub_model" => true,
			"documentation" => "https://battmoteam.github.io/BattMo.jl/dev/manuals/user_guide/pxd_model",
			"description" => """Framework defining the dimensionality of the electrochemical model. Examples: "P2D", "P4D Pouch". """,
		),
		"SEIModel" => Dict(
			"type" => String,
			"options" => ["Bolay"],
			"is_sub_model" => true,
			"context_type_iri" => nothing,
			"description" => """Which SEI model is used. For instance: "Bolay" """,
			"documentation" => "https://battmoteam.github.io/BattMo.jl/dev/manuals/user_guide/sei_model",
		),
		"ReactionRateConstant" => Dict(
			"type" => String,
			"options" => ["UserDefined", "TemperatureDependent"],
			"context_type" => "ReactionRateConstant",
			"context_type_iri" => "https://w3id.org/emmo/domain/battery#battery_b1921f7b_afac_465a_a275_26f929f7f936",
			"is_sub_model" => true,
			"documentation" => "https://battmoteam.github.io/BattMo.jl/dev/manuals/user_guide/pxd_model",
			"description" => """When set to UserDefined, the reaction rate constant will be a required cell parameter of type Function, String, Dict, or Real. When set to TemperatureDependent, an internal function will be used to calculate the reaction rate constant and some extra cell parameters will be required: ActivationEnergyOfReaction. Take a look into the documentation for more information.""",
		),
		"TransportInSolid" => Dict(
			"type" => String,
			"options" => ["FullDiffusion"],
			"is_sub_model" => true,
			"context_type_iri" => nothing,
			"description" => """Which model is used to describe the intercalant diffusion in the solid particles. Example "FullDiffusion". """,
		),
		"CurrentCollectors" => Dict(
			"type" => String,
			"options" => ["Generic"],
			"context_type" => "CurrentCollectors",
			"context_type_iri" => nothing,
			"is_sub_model" => true,
			"description" => "Which model describes the current collectors.",
		),
		"GridResolutionHeight" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 100,
			"context_type" => "Cell",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the height of the cell (used in P4D cylindrical)",
		),
		"GridResolutionAngular" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 100,
			"context_type" => "Cell",
			"context_type_iri" => nothing,
			"description" => "Number of discretisation angles for a cylindrical cell (used in P4D cylindrical)",
		),
		"GridResolutionElectrodeWidth" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type" => "GridResolutionPositiveElectrode",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the width dimension of the electrode.",
		),
		"GridResolutionElectrodeLength" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the length dimension of the electrode.",
		),
		"GridResolutionPositiveElectrodeCoating" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the thickness dimension of the positive electrode.",
		),
		"GridResolutionPositiveElectrodeActiveMaterial" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the radial pseudo dimension of the positive electrode active material particles.",
		),
		"GridResolutionNegativeElectrodeCoating" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the thickness dimension of the negative electrode.",
		),
		"GridResolutionPositiveElectrodeCurrentCollector" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the thickness dimension of the positive electrode current collector.",
		),
		"GridResolutionPositiveElectrodeCurrentCollectorTabWidth" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => nothing,
			"description" => "In the current collector tab at the positive electrode, the number of grid points along the width dimension of the tab's face.",
		),
		"GridResolutionPositiveElectrodeCurrentCollectorTabLength" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "In the current collector tab at the positive electrode, the number of grid points along the length dimension of the tab's face.",
		),
		"GridResolutionNegativeElectrodeCurrentCollector" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "Number of grid points along the thickness dimension of the negative electrode current collector.",
		),
		"GridResolutionNegativeElectrodeCurrentCollectorTabWidth" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "In the current collector tab at the negative electrode, the number of grid points along the width dimension of the tab's face.",
		),
		"GridResolutionNegativeElectrodeCurrentCollectorTabLength" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "In the current collector tab at the negative electrode, the number of grid points along the length dimension of the tab's face.",
		),
		"GridResolutionNegativeElectrodeActiveMaterial" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "Number of grid points along the radial pseudo dimension of the negative electrode active material particles.",
		),
		"GridResolutionSeparator" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "Number of grid points along the thickness dimension of the separator.",
		),
		"Grid" => Dict(
			"type" => Vector,
			"context_type" => "Grid",
			"context_type_iri" => nothing,
			"description" => "Vector storing the numerical representation of the computational grid discretizing the spatial representation of the cell.",
		),
		"RampUp" => Dict(
			"type" => String,
			"options" => ["Sinusoidal"],
			"context_type" => "RampUp",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_rampup",
			"documentation" => "https://battmoteam.github.io/BattMo.jl/dev/manuals/user_guide/ramp_up",
			"is_sub_model" => true,
			"description" => """Type of signal of electric current used to initialize the cell simulation. Example: "Sinusoidal".""",
		),
		"RampUpSteps" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 100,
			"context_type" => "RampUpSteps",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_rampup_steps",
			"description" => "Number of ramp-up steps applied to initialize the cell simulation.",
		),
		"RampUpTime" => Dict(
			"type" => Int,
			"min_value" => 0,
			"max_value" => 500,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"context_type" => "RampUpTime",
			"context_type_iri" => nothing,
			"description" => "Ramp up time duration applied to initialize the cell simulation.",
		),
		"TimeStepDuration" => Dict(
			"max_value" => 500,
			"min_value" => 1,
			"context_type" => "StepDuration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_85e39686_9658_4c74_bb91_a935704c174a",
			"description" => "Duration of each time step in simulations",
			"type" => Real,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo/domain/emmo#Second",
		))

	return meta_data
end
