export get_simulation_settings_meta_data

function get_simulation_settings_meta_data()

	meta_data = Dict(
		"HeightGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 100,
			"category" => "SimulationSettings",
			"context_type" => "Cell",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the height of the cell (used in P4D cylindrical)",
		),
		"AngularGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 100,
			"category" => "SimulationSettings",
			"context_type" => "Cell",
			"context_type_iri" => nothing,
			"description" => "Number of discretisation angles for a cylindrical cell (used in P4D cylindrical)",
		),
		"ElectrodeWidthGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type" => "GridPointsPositiveElectrode",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the width dimension of the electrode.",
		),
		"ElectrodeLengthGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the length dimension of the electrode.",
		),
		"PositiveElectrodeCoatingGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the thickness dimension of the positive electrode.",
		),
		"PositiveElectrodeParticleGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the radial pseudo dimension of the positive electrode active material particles.",
		),
		"NegativeElectrodeCoatingGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the thickness dimension of the negative electrode.",
		),
		"PositiveElectrodeCurrentCollectorGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => nothing,
			"description" => "Number of grid points along the thickness dimension of the positive electrode current collector.",
		),
		"PositiveElectrodeCurrentCollectorTabWidthGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => nothing,
			"description" => "In the current collector tab at the positive electrode, the number of grid points along the width dimension of the tab's face.",
		),
		"PositiveElectrodeCurrentCollectorTabLengthGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "In the current collector tab at the positive electrode, the number of grid points along the length dimension of the tab's face.",
		),
		"NegativeElectrodeCurrentCollectorGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "Number of grid points along the thickness dimension of the negative electrode current collector.",
		),
		"NegativeElectrodeCurrentCollectorTabWidthGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "In the current collector tab at the negative electrode, the number of grid points along the width dimension of the tab's face.",
		),
		"NegativeElectrodeCurrentCollectorTabLengthGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "In the current collector tab at the negative electrode, the number of grid points along the length dimension of the tab's face.",
		),
		"NegativeElectrodeParticleGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "Number of grid points along the radial pseudo dimension of the negative electrode active material particles.",
		),
		"SeparatorGridPoints" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 1000,
			"category" => "SimulationSettings",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_47608fd0_cc0d_457e_9141_051935029e3a",
			"description" => "Number of grid points along the thickness dimension of the separator.",
		),
		"Grid" => Dict(
			"type" => Vector,
			"category" => "SimulationSettings",
			"context_type" => "Grid",
			"context_type_iri" => nothing,
			"description" => "Vector storing the numerical representation of the computational grid discretizing the spatial representation of the cell.",
		),
		"RampUp" => Dict(
			"type" => String,
			"options" => ["Sinusoidal"],
			"category" => "SimulationSettings",
			"context_type" => "RampUp",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_rampup",
			"documentation" => "https://battmoteam.github.io/BattMo.jl/dev/manuals/user_guide/ramp_up",
			"category" => "ModelSettings",
			"description" => """Type of signal of electric current used to initialize the cell simulation. Example: "Sinusoidal".""",
		),
		"RampUpSteps" => Dict(
			"type" => Int,
			"min_value" => 1,
			"max_value" => 100,
			"category" => "SimulationSettings",
			"context_type" => "RampUpSteps",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_rampup_steps",
			"description" => "Number of ramp-up steps applied to initialize the cell simulation.",
		),
		"RampUpTime" => Dict(
			"type" => Int,
			"min_value" => 0,
			"max_value" => 500,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"category" => "SimulationSettings",
			"context_type" => "RampUpTime",
			"context_type_iri" => nothing,
			"description" => "Ramp up time duration applied to initialize the cell simulation.",
		),
		"TimeStepDuration" => Dict(
			"max_value" => 500,
			"min_value" => 1,
			"category" => "SimulationSettings",
			"context_type" => "StepDuration",
			"context_type_iri" => "https://w3id.org/emmo/domain/electrochemistry#electrochemistry_85e39686_9658_4c74_bb91_a935704c174a",
			"description" => "Duration of each time step in simulations",
			"type" => Real,
			"unit" => "s",
			"unit_name" => "emmo:Second",
			"unit_iri" => "https://w3id.org/emmo/domain/emmo#Second",
		),
	)
	return meta_data

end
