name: test
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.13.0,<2.0.0
  - pyjuliacall>=0.9.28
  - pytest>=8.4.2
  - pytest-cov>=4.1.0
  - pandas>=2.3.3
  - plotly>=5.15.0
  - scipy>=1.10.1
